services:
  postgres:
    image: postgres:16
    container_name: gaming_postgres
    environment:
      POSTGRES_DB: gaming_postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:8.2.5-bookworm
    container_name: gaming_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

volumes:
  pgdata: